# Generated by Django 4.2.5 on 2023-09-17 22:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'generos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_livro', models.CharField(default='adimin', max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(default='admin', max_length=255)),
                ('editora', models.CharField(default='admin', max_length=255)),
                ('descrição', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('slug', models.SlugField(max_length=255)),
                ('quantidade', models.IntegerField(default=1)),
                ('reserva', models.IntegerField(default=0)),
                ('no_estoque', models.BooleanField(default=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data_publicacao', models.DateField(default=datetime.date.today)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='biblioteca.category')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_creator', to=settings.AUTH_USER_MODEL)),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='biblioteca.genero')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-criado',),
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
