# Generated by Django 4.2.7 on 2023-11-13 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='adicionar_reserva',
            field=models.ManyToManyField(blank=True, related_name='reservasp', to='biblioteca.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='adicionar_reserva',
            field=models.ManyToManyField(blank=True, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='lista_desejos',
            field=models.ManyToManyField(blank=True, related_name='lista_desejosp', to='biblioteca.product'),
        ),
    ]
