# Generated by Django 4.2.7 on 2023-11-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_perfil_adicionar_reserva_product_adicionar_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_reserva',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
