# Generated by Django 4.2.3 on 2023-07-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_product_options_rename_author_product_autor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'generos',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='editora',
            field=models.CharField(default='admin', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='reserva',
            field=models.IntegerField(default=0),
        ),
    ]
