# Generated by Django 4.2.3 on 2023-07-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_genero_product_editora_product_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='biblioteca.genero', default=1),
),
    ]
