# Generated by Django 4.2.3 on 2023-07-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_product_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genero',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
