# Generated by Django 4.2.3 on 2023-07-23 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_genero_product_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_publicacao',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
