# Generated by Django 4.2.3 on 2023-07-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='disponivel',
        ),
    ]
