# Generated by Django 4.2.3 on 2023-09-16 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteca', '0013_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='reservar',
        ),
        migrations.AddField(
            model_name='product',
            name='lista_desejo',
            field=models.ManyToManyField(blank=True, related_name='reservados', to=settings.AUTH_USER_MODEL),
        ),
    ]
