# Generated by Django 4.2.3 on 2023-09-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0014_remove_perfil_reservar_product_lista_desejo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lista_desejo',
        ),
    ]
